# Test your FastAPI endpoints

GET http://127.0.0.1:8000/
Accept: application/json

###

GET http://127.0.0.1:8000/hello/User
Accept: application/json

###
POST http://127.0.0.1:8000/api/academic/login
Content-Type: application/json

{
  "username": "20230502036",
  "password": "ZZh123456"
}

###
GET http://127.0.0.1:8000/api/academic/semesters
X-Academic-Session: 69efc6d911874d5a9ed89d4410867eb9
Accept: application/json

###
GET http://127.0.0.1:8000/api/academic/grades?semester=2024-2025-1
X-Academic-Session: 69efc6d911874d5a9ed89d4410867eb9
Accept: application/json

###
GET http://127.0.0.1:8000/api/academic/me
X-Academic-Session: 69efc6d911874d5a9ed89d4410867eb9
Accept: application/json

###
GET http://localhost:8000/api/academic/schedule
X-Academic-Session: 5e31fe7b47d9490386fa6efc6b509ea7
Accept: application/json