"""create weather tables

Revision ID: 6a9cc1520837
Revises: 7f812f428477
Create Date: 2025-12-13 03:51:06.774389

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6a9cc1520837'
down_revision: Union[str, Sequence[str], None] = '7f812f428477'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('weather_cache',
    sa.Column('city', sa.Text(), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('weather_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('cached_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expiration_minutes', sa.Integer(), server_default=sa.text('30'), nullable=False),
    sa.PrimaryKeyConstraint('city')
    )
    op.create_index('idx_weather_cache_data_gin', 'weather_cache', ['weather_data'], unique=False, postgresql_using='gin')
    op.create_table('weather_snapshot',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('city', sa.Text(), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('data_time', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('weather_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_weather_snapshot_city_time', 'weather_snapshot', ['city', 'data_time'], unique=False)
    op.create_index('idx_weather_snapshot_data_gin', 'weather_snapshot', ['weather_data'], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_weather_snapshot_data_gin', table_name='weather_snapshot', postgresql_using='gin')
    op.drop_index('idx_weather_snapshot_city_time', table_name='weather_snapshot')
    op.drop_table('weather_snapshot')
    op.drop_index('idx_weather_cache_data_gin', table_name='weather_cache', postgresql_using='gin')
    op.drop_table('weather_cache')
    # ### end Alembic commands ###
