"""academic tables

Revision ID: 768374bba21c
Revises: a0a6429066e8
Create Date: 2025-12-15 05:00:41.121758

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '768374bba21c'
down_revision: Union[str, Sequence[str], None] = 'a0a6429066e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('academic_user',
    sa.Column('student_id', sa.String(length=64), nullable=False),
    sa.Column('account', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('college', sa.String(length=256), nullable=True),
    sa.Column('major', sa.String(length=256), nullable=True),
    sa.Column('class_name', sa.String(length=128), nullable=True),
    sa.Column('enrollment_year', sa.String(length=16), nullable=True),
    sa.Column('study_level', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('student_id')
    )
    op.create_table('academic_grade',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.String(length=64), nullable=False),
    sa.Column('semester', sa.String(length=64), nullable=False),
    sa.Column('course_code', sa.String(length=64), nullable=True),
    sa.Column('course_name', sa.String(length=256), nullable=True),
    sa.Column('credit', sa.String(length=32), nullable=True),
    sa.Column('score', sa.String(length=32), nullable=True),
    sa.Column('gpa', sa.String(length=32), nullable=True),
    sa.Column('raw_hash', sa.String(length=40), nullable=False),
    sa.Column('raw_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['academic_user.student_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'semester', 'raw_hash', name='uq_academic_grade_student_semester_hash')
    )
    op.create_index(op.f('ix_academic_grade_fetched_at'), 'academic_grade', ['fetched_at'], unique=False)
    op.create_index(op.f('ix_academic_grade_semester'), 'academic_grade', ['semester'], unique=False)
    op.create_index(op.f('ix_academic_grade_student_id'), 'academic_grade', ['student_id'], unique=False)
    op.create_index('ix_academic_grade_student_semester_time', 'academic_grade', ['student_id', 'semester', 'fetched_at'], unique=False)
    op.create_table('academic_schedule',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.String(length=64), nullable=False),
    sa.Column('semester', sa.String(length=64), nullable=False),
    sa.Column('current_week', sa.Integer(), nullable=True),
    sa.Column('raw_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['academic_user.student_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'semester', name='uq_academic_schedule_student_semester')
    )
    op.create_index(op.f('ix_academic_schedule_fetched_at'), 'academic_schedule', ['fetched_at'], unique=False)
    op.create_index(op.f('ix_academic_schedule_semester'), 'academic_schedule', ['semester'], unique=False)
    op.create_index(op.f('ix_academic_schedule_student_id'), 'academic_schedule', ['student_id'], unique=False)
    op.create_table('academic_snapshot',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.String(length=64), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('scope', sa.String(length=64), nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['academic_user.student_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_academic_snapshot_fetched_at'), 'academic_snapshot', ['fetched_at'], unique=False)
    op.create_index(op.f('ix_academic_snapshot_student_id'), 'academic_snapshot', ['student_id'], unique=False)
    op.create_index('ix_academic_snapshot_student_kind_scope_time', 'academic_snapshot', ['student_id', 'kind', 'scope', 'fetched_at'], unique=False)
    op.create_table('academic_schedule_course',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('schedule_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('teacher', sa.String(length=128), nullable=True),
    sa.Column('location', sa.String(length=256), nullable=True),
    sa.Column('weekday', sa.Integer(), nullable=False),
    sa.Column('start_section', sa.Integer(), nullable=False),
    sa.Column('end_section', sa.Integer(), nullable=False),
    sa.Column('week_range', sa.String(length=128), nullable=True),
    sa.Column('weeks', postgresql.ARRAY(sa.Integer()), nullable=False),
    sa.Column('raw_hash', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['schedule_id'], ['academic_schedule.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('schedule_id', 'raw_hash', name='uq_academic_schedule_course_schedule_hash')
    )
    op.create_index(op.f('ix_academic_schedule_course_schedule_id'), 'academic_schedule_course', ['schedule_id'], unique=False)
    op.create_index('ix_academic_schedule_course_schedule_weekday', 'academic_schedule_course', ['schedule_id', 'weekday'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_academic_schedule_course_schedule_weekday', table_name='academic_schedule_course')
    op.drop_index(op.f('ix_academic_schedule_course_schedule_id'), table_name='academic_schedule_course')
    op.drop_table('academic_schedule_course')
    op.drop_index('ix_academic_snapshot_student_kind_scope_time', table_name='academic_snapshot')
    op.drop_index(op.f('ix_academic_snapshot_student_id'), table_name='academic_snapshot')
    op.drop_index(op.f('ix_academic_snapshot_fetched_at'), table_name='academic_snapshot')
    op.drop_table('academic_snapshot')
    op.drop_index(op.f('ix_academic_schedule_student_id'), table_name='academic_schedule')
    op.drop_index(op.f('ix_academic_schedule_semester'), table_name='academic_schedule')
    op.drop_index(op.f('ix_academic_schedule_fetched_at'), table_name='academic_schedule')
    op.drop_table('academic_schedule')
    op.drop_index('ix_academic_grade_student_semester_time', table_name='academic_grade')
    op.drop_index(op.f('ix_academic_grade_student_id'), table_name='academic_grade')
    op.drop_index(op.f('ix_academic_grade_semester'), table_name='academic_grade')
    op.drop_index(op.f('ix_academic_grade_fetched_at'), table_name='academic_grade')
    op.drop_table('academic_grade')
    op.drop_table('academic_user')
    # ### end Alembic commands ###
