"""create weather tables

Revision ID: 9a85d9c7d23b
Revises: 
Create Date: 2025-12-12 20:28:34.666916

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a85d9c7d23b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_weather_cache_city'), table_name='weather_cache')
    op.drop_index(op.f('idx_weather_cache_data_gin'), table_name='weather_cache', postgresql_using='gin')
    op.drop_index(op.f('idx_snapshot_city_time'), table_name='weather_snapshot')
    op.drop_index(op.f('idx_snapshot_data_gin'), table_name='weather_snapshot', postgresql_ops={'weather_data': 'jsonb_path_ops'}, postgresql_using='gin')
    op.drop_index(op.f('idx_weather_snapshot_city_time'), table_name='weather_snapshot')
    op.drop_index(op.f('idx_weather_snapshot_data_gin'), table_name='weather_snapshot', postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_weather_snapshot_data_gin'), 'weather_snapshot', ['weather_data'], unique=False, postgresql_using='gin')
    op.create_index(op.f('idx_weather_snapshot_city_time'), 'weather_snapshot', ['city', sa.literal_column('data_time DESC')], unique=False)
    op.create_index(op.f('idx_snapshot_data_gin'), 'weather_snapshot', ['weather_data'], unique=False, postgresql_ops={'weather_data': 'jsonb_path_ops'}, postgresql_using='gin')
    op.create_index(op.f('idx_snapshot_city_time'), 'weather_snapshot', ['city', sa.literal_column('data_time DESC')], unique=False)
    op.create_index(op.f('idx_weather_cache_data_gin'), 'weather_cache', ['weather_data'], unique=False, postgresql_using='gin')
    op.create_index(op.f('idx_weather_cache_city'), 'weather_cache', ['city'], unique=False)
    # ### end Alembic commands ###
