"""platform tables

Revision ID: c7d72bfa96e8
Revises: b74a5838ca01
Create Date: 2025-12-15 07:40:57.671511

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c7d72bfa96e8'
down_revision: Union[str, Sequence[str], None] = 'b74a5838ca01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_analysis_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('semester', sa.String(length=32), nullable=False),
    sa.Column('prompt_name', sa.String(length=64), nullable=False),
    sa.Column('input_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('output_text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_analysis_history_user_id'), 'ai_analysis_history', ['user_id'], unique=False)
    op.create_table('ai_prompt_template',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('platform_user',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('student_id', sa.String(length=64), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_platform_user_role'), 'platform_user', ['role'], unique=False)
    op.create_index(op.f('ix_platform_user_student_id'), 'platform_user', ['student_id'], unique=False)
    op.create_index(op.f('ix_platform_user_username'), 'platform_user', ['username'], unique=True)
    op.create_table('weather_switch',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('last_backup_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('weather_switch')
    op.drop_index(op.f('ix_platform_user_username'), table_name='platform_user')
    op.drop_index(op.f('ix_platform_user_student_id'), table_name='platform_user')
    op.drop_index(op.f('ix_platform_user_role'), table_name='platform_user')
    op.drop_table('platform_user')
    op.drop_table('ai_prompt_template')
    op.drop_index(op.f('ix_ai_analysis_history_user_id'), table_name='ai_analysis_history')
    op.drop_table('ai_analysis_history')
    # ### end Alembic commands ###
